### ISSUE TITLE
Updating to the 2.0 .NET SDK

### ISSUE THREAD

**Issue by jskeet** [cloudevents/sdk-powershell#2]
We're getting closer to releasing 2.0 of the [.NET SDK](https://github.com/cloudevents/sdk-csharp) - which obviously may break the PowerShell SDK.

We haven't released a 2.0 beta for a while, but when I've got the last few "big" pieces in, I'll want to do that... at which point it might be a good idea to create a beta branch of this repo that depends on the 2.0 beta, so we can find breakages early.
Please let me know how I can help.

**Comment by dmilov** [comment]
We plan to release version 0.X of the PowerShell SDK based on .NET SDK v1.3 soon. After that release, we can create a beta branch here that depends on .NET SDK 2.0 beta.

**Comment by jskeet** [comment]
SGTM. I'll attempt to remember to ping this issue when we've released a beta.2 version, as that will look pretty close to the final API surface.

**Comment by jskeet** [comment]
Ping! We released the 2.0.0-beta.2 version today. @dmilov please let me know if you'd like me to help with updating the PowerShell SDK - but without actually knowing any PowerShell...

**Comment by dmilov** [comment]
Hi @jskeet 

I migrated the PS Sdk to consume the C# Sdk beta in a `beta` branch of my fork repo https://github.com/dmilov/sdk-powershell/tree/beta

I tried to keep the PS SDK backwards compatible but there will be issues with the `time` representation, everything else looks good at least for now. I found some bugs in PS SDK implementation thanks to the new validations in the C# SDK.

We've been still working on streamlining the release process for the PS SDK, once we polished that I'll move the beta branch to the official repo.

**Comment by jskeet** [comment]
That's great news. My vague suggestion is that you *do* actually take breaking changes, but don't merge them into your main branch yet. When the C# SDK releases 2.0 GA, you might then want to update your branch and take all the breaking changes in one go.

My assumptions for that are:

- You don't want to break early adopters multiple times
- You haven't actually released a GA version of the PS SDK yet
- The C# SDK 2.0+ is the version that will actually be widespread over time

Feel free to challenge any of those assumptions :)

**Comment by embano1** [comment]
@jskeet you're right, we are not at a stable API/GA release level yet (0.2.0 as per gallery version). I think we can play a bit with the 2.0 SDK but not delay it too much as there is already adoption of the current module. We haven't heard back from users about required API changes, which is a good sign.

So we could potentially release a v1.0.0 stable API in the coming weeks.

**Comment by jskeet** [comment]
Good to know, thanks. I'm really hoping to get the C# SDK to 2.0 GA in the next 4-6 weeks. Hopefully that will fit in with your timelines.
